### ISSUE TITLE
AppCSXCAD view window is corrupted

### ISSUE THREAD

**Issue by kb1vc** [thliebig/openEMS-Project#173]
I’ve built the openEMS tools from openEMS-Project tag v0.0.36. 
The platform is Fedora 39
libvtk is version 9.2.6
Qt is qt5

I’m running under an x11 server. 

This is what it looks like when it comes up. (From the command line, or from an octave script.) 

![Screenshot 2023-12-29 at 7 52 15 PM](https://github.com/thliebig/openEMS-Project/assets/14140298/5af5217f-0946-450a-b2d7-1e3f04899b0e)

The background can vary, but this is typical. 

Any ideas?   (I’m willing to experiment.)

**Comment by biergaizi** [comment]
This is probably a 3D graphics driver issue that has nothing to do with AppCSXCAD. I recommend checking whether other 3D applications in the same machine are functional. You can also try setting `LIBGL_ALWAYS_SOFTWARE=1` to see whether AppCSXCAD works in software rendering mode.
