### ISSUE TITLE
Build fails with Open MPI 5.0 and newer due to missing C++ bindings

### ISSUE THREAD

**Issue by mluessi** [thliebig/openEMS-Project#189]
The C++ bindings that openEMS uses have been removed from Open MPI 5.0. 

It would be best if openEMS used the C bindings, so it works with Open MPI 5 and later.

**Comment by thliebig** [comment]
This is only a "meta-project" for openEMS to combine all the required parts and e.g. provide build instructions. Please open an issue for openEMS (not openEMS-Project) instead?
