### ISSUE TITLE
The problem of calculating the S-parameters of Magic tee and a rectangular waveguide

### ISSUE THREAD

**Issue by Sheptor** [thliebig/openEMS-Project#193]
# The problem of calculating the S-parameters of Magic tee and a rectangular waveguide
## Introduction

Hello! I am engaged in research on the propagation of an electromagnetic wave in a segment of the magic tee waveguide with cross section 23x10mm^2. But in the simulation results, the sum of the squares of the s-parameters is not equal to 1 (figure 2). I tried to create a waveguide in different ways:
1. Import from `stl` file;
2. Creating waveguide metal walls using AddBox;
3. Filling the simulation space with metal and adding a waveguide cavity using AddBox with epsilon=1 (figure 1). 

### Figure 1. Magic tee (metall hidden)
![magic_tee_image](https://github.com/Sheptor/test-issue/assets/141247706/2d89ae8f-c891-4b9d-ae9b-62414ed17961)

### Figure 2. Magic tee (s-parameters)
![magic_tee_s_params](https://github.com/Sheptor/test-issue/assets/141247706/bee198d2-4822-4d5e-8928-74c8adbf1f56)

# Problem
To verify the results, a rectangular waveguide with a size of 23x10mm^2 was modeled. In the first case: the boundaries of the grid coincide with the section of the waveguide. in the second case, the border is shifted and metal is added to the place of free space (figures 5 - 8).

### Figгre 3. Empty waveguide
![waveguide_filled_metal_and_air](https://github.com/Sheptor/test-issue/assets/141247706/0f8ecf65-7837-4959-8720-b9b488d47ccb)

### Figure 4. Empty waveguide (s-parameters)
![s_params_fill_air](https://github.com/Sheptor/test-issue/assets/141247706/f1cbbfe3-e6d3-4f7d-8106-2d67b621bf1c)

### Figure 5. Waveguide with thin metal walls (metal walls hidden)
![Waveguide with thin metal walls (metal walls hidden)](https://github.com/Sheptor/test-issue/assets/141247706/9f4edcb0-68e9-437d-a13c-d551194d9e13)

### Figure 6. Waveguide with thin metal walls (metal walls hidden) (s-parameters)
![Waveguide with thin metal walls (metal walls hidden) (s-parameters)](https://github.com/Sheptor/test-issue/assets/141247706/b6239589-ab4b-40bf-a99b-752a82aeb280)

### Figure 7. The walls of the waveguide are larger than the cavity of the waveguide
![large walls](https://github.com/Sheptor/test-issue/assets/141247706/afc3f245-15ee-49f7-b0ae-8b8dda8bbcda)

### Figure 8. The walls of the waveguide are larger than the cavity of the waveguide (s-parameters)
![large walls (s-parameters)](https://github.com/Sheptor/test-issue/assets/141247706/f55597cb-5c00-4a78-966a-238b5026ccdd)

# Code
The simulation was carried out using both the python interface and the octave interface:
https://github.com/Sheptor/test-issue

**Comment by thliebig** [comment]
I have not yet had the time to look into your problem in more detail, but from the looks this would have been better suited for the Discussion section and not as an issue? 
I mean it is always possible that an actual issue may be found causing your questions, but usually this is more a "how to use openEMS"  question?

**Comment by Sheptor** [comment]
I agree that this applies to the discussion section, but due to inattention, this problem has been posted in this section. A few hours later, I noticed this and duplicated it in the discussion section https://github.com/thliebig/openEMS-Project/discussions/194.
I conducted additional studies with an smoothed grid, the results of which I added to the discussion.
