### ISSUE TITLE
About installing cp310 vs cp311

### ISSUE THREAD

**Issue by Basilisvirus** [thliebig/openEMS-Project#243]
Why under  `openEMS_v0.0.36\openEMS\python` there are both cp311 and cp310 versions available to install? I believe cp310 is old(er) version. Is there any reason to prefer cp310 over cp311?

![{29505762-E613-469C-8F7F-8FA87748E9B3}](https://github.com/user-attachments/assets/ef119ab3-8c40-4643-9668-f881df0cd78b)

The [documentation](https://docs.openems.de/python/install.html#python-windows-install) sets as example installing cp310. But does not state anything about cp311.

**Comment by thliebig** [comment]
The only reason is that I do not want to force people to use a certain python version just because of openEMS. Nothing else...

**Comment by Basilisvirus** [comment]
but some of the examples dont run with both versions. cp310 looks more compatible with the examples. Also, with cp10 I managed to run a electric/magnetic field simulation while with cp311 it showed weird results.

If I make an issue here on the weird results I got on my simulation with cp311 would I get any help here regarding the reason behing the weird results?

**Comment by thliebig** [comment]
This is the first time I hear about issues like this. Both are linked against the very same openEMS.dll and thus this is surprising... Maybe you can state which examples? I currently have no Windows machine but maybe someone can confirm your finding... BTW I always build this using WinPython... Not sure if this matters...
