### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by KaboomPhysicist** [thliebig/openEMS-Project#59]
There are several links all over the internet and even in the README file of this repository pointing to inexistent subpages of www.openems.de 
Is there any possibility to deploy that old material in the temporal website? Is it going to be back someday?

**Comment by biergaizi** [comment]
If my understanding is correct, the original server is permanently offline and it's never going to come back again. But most materials are archived at https://wiki.openems.de/. If you replace "www" with "wiki", it should work most of the time.
