### ISSUE TITLE
Can OpenEMS find far-field electric field phase information at unit radius?

### ISSUE THREAD

**Issue by XDAChen** [thliebig/openEMS-Project#73]
### Discussed in https://github.com/thliebig/openEMS-Project/discussions/72

<div type='discussions-op-text'>

<sup>Originally posted by **XDAChen** May 19, 2023</sup>
I want to obtain information about an antenna's far-field phase change relative to its phase center at a unit radius, r using OpenEMS. In HFSS I had done it with far-field result --> rE --> cang_ang. I am not sure if openEMS can provide the same information. 

While I am looking at the nf2ff documentation, if I understand correctly, I set my antenna's phase center as default [0,0,0], and I can compute the electric field strength at a radius r. If it is a complex number I can post-process the complex field strength to find the angle, which would be the phase shift relative to the antenna phase center?

Anyone had done a similar thing before?

</div>

**Comment by thliebig** [comment]
Please use the discussion section to get answers to questions about the openEMS usage.
